server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rongxiaotong?serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=UTF-8&useSSL=false
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: uploadService8007
  web:
    resources:
      static-locations:
      -  file:${application.upload-path}
      - file:D:/nginx/html/images/file  # 改成父目录（包含avatar子目录）
      #- file:D:/nginx/html/images/file/order  # nginx的order图片目录
      #- file:D:/nginx/html/images/file/avatar  # nginx的avatar图片目录
      #- file:d:/rongxiaotong/file/video  # 视频目录
  mvc:
    #static-path-pattern: file:D:\nginx\html\images\file/order,file:D:\nginx\html\images\file/avatar,file:d:/rongxiaotong/file/video
    #static-path-pattern: /file/**
    static-path-pattern: /static/**  # 把/file改成/static，避开接口冲突
  data:
    redis:
      host: localhost
      port: 6379
application:
    upload-path: d:/rongxiaotong/file

# PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#nginx存放图片的路径
file:
  location:
    directory: D:\nginx\html\images\file
# 支付宝 appId,私钥，支付宝公钥
alipay:
  info:
    appId:
    privateKey:
    alipayPublicKey:



